AWSTemplateFormatVersion: '2010-09-09'
Description: 'Comprehensive EventBridge Rules for Medical Pharmaceutical Data Ingestion'

Parameters:
  Environment:
    Type: String
    Default: dev
  
  DataIngestionFunctionArn:
    Type: String
    Description: ARN of the comprehensive data ingestion Lambda function

Resources:
  # High-frequency ingestion (every 2 hours)
  PubMedIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'pubmed-comprehensive-ingestion-${Environment}'
      Description: 'Comprehensive PubMed data ingestion every 2 hours'
      ScheduleExpression: 'rate(2 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: PubMedComprehensiveTarget
          Input: !Sub |
            {
              "source": "pubmed",
              "environment": "${Environment}",
              "comprehensive": true,
              "search_depth": "enhanced"
            }

  # Clinical trials ingestion (every 6 hours)
  ClinicalTrialsIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'clinicaltrials-comprehensive-ingestion-${Environment}'
      Description: 'Comprehensive clinical trials ingestion every 6 hours'
      ScheduleExpression: 'rate(6 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: ClinicalTrialsComprehensiveTarget
          Input: !Sub |
            {
              "source": "clinicaltrials",
              "environment": "${Environment}",
              "comprehensive": true,
              "include_phases": ["Phase 1", "Phase 2", "Phase 3"]
            }

  # FDA data ingestion (every 4 hours)
  FDAIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'fda-comprehensive-ingestion-${Environment}'
      Description: 'Comprehensive FDA data ingestion every 4 hours'
      ScheduleExpression: 'rate(4 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: FDAComprehensiveTarget
          Input: !Sub |
            {
              "source": "fda",
              "environment": "${Environment}",
              "comprehensive": true,
              "endpoints": ["adverse_events", "drug_labels", "drug_approvals"]
            }

  # EMA data ingestion (daily)
  EMAIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'ema-ingestion-${Environment}'
      Description: 'EMA data ingestion daily'
      ScheduleExpression: 'rate(1 day)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: EMAIngestionTarget
          Input: !Sub |
            {
              "source": "ema",
              "environment": "${Environment}",
              "region": "eu"
            }

  # Patent data ingestion (daily)
  PatentIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'patent-ingestion-${Environment}'
      Description: 'Patent data ingestion daily'
      ScheduleExpression: 'rate(1 day)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: PatentIngestionTarget
          Input: !Sub |
            {
              "source": "patents",
              "environment": "${Environment}",
              "sources": ["uspto", "epo"]
            }

  # News ingestion (every 3 hours)
  NewsIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'pharma-news-ingestion-${Environment}'
      Description: 'Pharmaceutical news ingestion every 3 hours'
      ScheduleExpression: 'rate(3 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: NewsIngestionTarget
          Input: !Sub |
            {
              "source": "news",
              "environment": "${Environment}",
              "sources": ["biopharma_dive", "fierce_pharma", "stat_news"]
            }

  # Conference data ingestion (weekly)
  ConferenceIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'conference-ingestion-${Environment}'
      Description: 'Medical conference data ingestion weekly'
      ScheduleExpression: 'rate(7 days)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: ConferenceIngestionTarget
          Input: !Sub |
            {
              "source": "conferences",
              "environment": "${Environment}",
              "conferences": ["asco", "esmo", "aacr", "ash", "sitc"]
            }

  # SEC filings ingestion (daily)
  SECIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'sec-filings-ingestion-${Environment}'
      Description: 'SEC filings ingestion daily'
      ScheduleExpression: 'rate(1 day)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: SECIngestionTarget
          Input: !Sub |
            {
              "source": "sec",
              "environment": "${Environment}",
              "filing_types": ["10-K", "10-Q", "8-K"]
            }

  # Comprehensive ingestion (daily full sweep)
  ComprehensiveIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'comprehensive-full-ingestion-${Environment}'
      Description: 'Full comprehensive data ingestion daily'
      ScheduleExpression: 'cron(0 2 * * ? *)'  # 2 AM daily
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: ComprehensiveFullTarget
          Input: !Sub |
            {
              "source": "all",
              "environment": "${Environment}",
              "mode": "comprehensive",
              "deep_analysis": true
            }

  # Real-time alert processing
  AlertProcessingRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'alert-processing-${Environment}'
      Description: 'Process high-priority alerts immediately'
      EventPattern:
        source: ['ci.alert.system']
        detail-type: ['High Priority Alert', 'Critical Alert']
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: AlertProcessingTarget
          Input: !Sub |
            {
              "source": "alert_processing",
              "environment": "${Environment}",
              "priority": "high"
            }

  # Lambda Permissions for all EventBridge rules
  PubMedIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PubMedIngestionRule.Arn

  ClinicalTrialsIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ClinicalTrialsIngestionRule.Arn

  FDAIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt FDAIngestionRule.Arn

  EMAIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EMAIngestionRule.Arn

  PatentIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PatentIngestionRule.Arn

  NewsIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt NewsIngestionRule.Arn

  ConferenceIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ConferenceIngestionRule.Arn

  SECIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SECIngestionRule.Arn

  ComprehensiveIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ComprehensiveIngestionRule.Arn

  AlertProcessingPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt AlertProcessingRule.Arn

Outputs:
  IngestionScheduleStatus:
    Description: 'Status of comprehensive ingestion schedules'
    Value: 'All ingestion rules configured and enabled'
  
  IngestionFrequency:
    Description: 'Data ingestion frequencies'
    Value: 'PubMed: 2h, ClinicalTrials: 6h, FDA: 4h, News: 3h, Others: Daily'