AWSTemplateFormatVersion: '2010-09-09'
Description: 'EventBridge Rules for Scheduled Data Ingestion'

Parameters:
  Environment:
    Type: String
    Default: dev
  
  DataIngestionFunctionArn:
    Type: String
    Description: ARN of the data ingestion Lambda function

Resources:
  # Scheduled Rules for Data Ingestion
  PubMedIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'pubmed-ingestion-${Environment}'
      Description: 'Trigger PubMed data ingestion every 6 hours'
      ScheduleExpression: 'rate(6 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: PubMedIngestionTarget
          Input: !Sub |
            {
              "source": "pubmed",
              "environment": "${Environment}"
            }

  ClinicalTrialsIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'trials-ingestion-${Environment}'
      Description: 'Trigger clinical trials ingestion daily'
      ScheduleExpression: 'rate(1 day)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: TrialsIngestionTarget
          Input: !Sub |
            {
              "source": "clinicaltrials",
              "environment": "${Environment}"
            }

  FDAIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'fda-ingestion-${Environment}'
      Description: 'Trigger FDA data ingestion every 4 hours'
      ScheduleExpression: 'rate(4 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataIngestionFunctionArn
          Id: FDAIngestionTarget
          Input: !Sub |
            {
              "source": "fda",
              "environment": "${Environment}"
            }

  # Lambda Permissions for EventBridge
  PubMedIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PubMedIngestionRule.Arn

  TrialsIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ClinicalTrialsIngestionRule.Arn

  FDAIngestionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt FDAIngestionRule.Arn

  # PHASE 3 - AI & DATA PIPELINES
  # AI Model Invocation Rules for Competitive Intelligence Analysis

  AIInsightsGenerationRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'ai-insights-generation-${Environment}'
      Description: 'Trigger AI insights generation for processed documents'
      EventPattern:
        source: ['ci.alert.system']
        detail-type: ['Document Processed']
        detail:
          status: ['completed']
      State: ENABLED
      Targets:
        - Arn: !Ref AIHandlerFunctionArn
          Id: AIInsightsTarget
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn

  AlertGenerationRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'alert-generation-${Environment}'
      Description: 'Trigger alert generation based on AI analysis'
      EventPattern:
        source: ['ci.alert.system']
        detail-type: ['AI Analysis Complete']
      State: ENABLED
      Targets:
        - Arn: !Ref AlertHandlerFunctionArn
          Id: AlertGenerationTarget
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn

  CompetitiveAnalysisRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'competitive-analysis-${Environment}'
      Description: 'Trigger competitive landscape analysis daily'
      ScheduleExpression: 'cron(0 2 * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !Ref CompetitiveAnalysisHandlerArn
          Id: CompetitiveAnalysisTarget
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: !Sub |
            {
              "analysisType": "competitive_landscape",
              "environment": "${Environment}",
              "includeHistoricalData": true
            }

  BrandIntelligenceAggregationRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'brand-intelligence-aggregation-${Environment}'
      Description: 'Aggregate brand intelligence data every 12 hours'
      ScheduleExpression: 'rate(12 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref BrandHandlerFunctionArn
          Id: BrandAggregationTarget
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: !Sub |
            {
              "operation": "aggregate_intelligence",
              "environment": "${Environment}"
            }

  DashboardDataRefreshRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'dashboard-data-refresh-${Environment}'
      Description: 'Refresh dashboard data every 4 hours'
      ScheduleExpression: 'rate(4 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref DashboardHandlerFunctionArn
          Id: DashboardRefreshTarget
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: !Sub |
            {
              "operation": "refresh_kpis",
              "environment": "${Environment}"
            }

  DataQualityCheckRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'data-quality-check-${Environment}'
      Description: 'Run data quality checks every 6 hours'
      ScheduleExpression: 'rate(6 hours)'
      State: ENABLED
      Targets:
        - Arn: !Ref DataQualityCheckFunctionArn
          Id: DataQualityTarget
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: !Sub |
            {
              "checkType": "comprehensive",
              "environment": "${Environment}"
            }

  # EventBridge Role for Lambda Invocation
  EventBridgeInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EventBridgeInvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ci-ai-handler-${Environment}'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ci-alert-handler-${Environment}'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ci-competitive-analysis-${Environment}'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ci-brand-handler-${Environment}'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ci-dashboard-handler-${Environment}'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ci-data-quality-${Environment}'

Parameters:
  AIHandlerFunctionArn:
    Type: String
    Description: ARN of the AI handler Lambda function
    Default: ''

  AlertHandlerFunctionArn:
    Type: String
    Description: ARN of the alert handler Lambda function
    Default: ''

  CompetitiveAnalysisHandlerArn:
    Type: String
    Description: ARN of the competitive analysis handler Lambda function
    Default: ''

  BrandHandlerFunctionArn:
    Type: String
    Description: ARN of the brand handler Lambda function
    Default: ''

  DashboardHandlerFunctionArn:
    Type: String
    Description: ARN of the dashboard handler Lambda function
    Default: ''

  DataQualityCheckFunctionArn:
    Type: String
    Description: ARN of the data quality check Lambda function
    Default: ''