AWSTemplateFormatVersion: '2010-09-09'
Description: 'Pharmaceutical CI Platform - Frontend Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  # Amplify App for Frontend
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub 'pharma-ci-frontend-${Environment}'
      Repository: 'https://github.com/your-repo/pharma-ci-frontend'
      Platform: WEB
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm install
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      EnvironmentVariables:
        - Name: REACT_APP_API_ENDPOINT
          Value: !Sub '${AIAPI}.execute-api.${AWS::Region}.amazonaws.com/prod'
        - Name: REACT_APP_REGION
          Value: !Ref AWS::Region
        - Name: REACT_APP_ENVIRONMENT
          Value: !Ref Environment

  # Amplify Branch
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      EnableAutoBuild: true
      Stage: PRODUCTION

Outputs:
  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppId'

  AmplifyURL:
    Description: Amplify App URL
    Value: !Sub 'https://${AmplifyBranch.BranchName}.${AmplifyApp.DefaultDomain}'
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyURL'