AWSTemplateFormatVersion: '2010-09-09'
Description: 'Production-Grade Pharmaceutical CI Platform - Frontend Stack'

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  GitHubRepo:
    Type: String
    Default: 'https://github.com/your-org/pharma-ci-frontend'
    Description: GitHub repository URL
  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub personal access token
  DomainName:
    Type: String
    Default: ''
    Description: Custom domain name (optional)
  CertificateArn:
    Type: String
    Default: ''
    Description: ACM certificate ARN for custom domain

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, '']]
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]

Resources:
  # Amplify App with production settings
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub 'pharma-ci-frontend-${Environment}'
      Repository: !Ref GitHubRepo
      AccessToken: !Ref GitHubToken
      Platform: WEB_COMPUTE
      BuildSpec: |
        version: 1
        applications:
          - frontend:
              phases:
                preBuild:
                  commands:
                    - npm ci --cache .npm --prefer-offline
                    - npm audit fix
                build:
                  commands:
                    - npm run build
                    - npm run test:coverage
              artifacts:
                baseDirectory: build
                files:
                  - '**/*'
              cache:
                paths:
                  - .npm/**/*
                  - node_modules/**/*
            appRoot: frontend
      EnvironmentVariables:
        - Name: REACT_APP_API_ENDPOINT
          Value: !Sub '{{resolve:ssm:/pharma-ci/${Environment}/api-endpoint}}'
        - Name: REACT_APP_REGION
          Value: !Ref AWS::Region
        - Name: REACT_APP_ENVIRONMENT
          Value: !Ref Environment
        - Name: REACT_APP_VERSION
          Value: !Sub '${Environment}-{{resolve:ssm:/pharma-ci/${Environment}/version:1}}'
        - Name: NODE_ENV
          Value: production
        - Name: GENERATE_SOURCEMAP
          Value: 'false'
      CustomRules:
        - Source: '/<*>'
          Target: '/index.html'
          Status: '404-200'
        - Source: '/api/<*>'
          Target: !Sub '{{resolve:ssm:/pharma-ci/${Environment}/api-endpoint}}/<*>'
          Status: '200'
      EnableBranchAutoDeletion: true
      IAMServiceRole: !GetAtt AmplifyRole.Arn

  # IAM Role for Amplify
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'AmplifyRole-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/pharma-ci/${Environment}/*'

  # Production Branch
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !If [!Equals [!Ref Environment, 'prod'], 'main', !Ref Environment]
      EnableAutoBuild: true
      EnablePullRequestPreview: !If [!Equals [!Ref Environment, 'prod'], false, true]
      Stage: !If [!Equals [!Ref Environment, 'prod'], 'PRODUCTION', 'DEVELOPMENT']
      EnvironmentVariables:
        - Name: REACT_APP_STAGE
          Value: !Ref Environment
      Framework: React
      EnablePerformanceMode: !If [!Equals [!Ref Environment, 'prod'], true, false]

  # Custom Domain (if provided)
  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Condition: HasCustomDomain
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      DomainName: !Ref DomainName
      CertificateSettings:
        CertificateType: !If [HasCertificate, 'CUSTOM', 'AMPLIFY_MANAGED']
        CertificateArn: !If [HasCertificate, !Ref CertificateArn, !Ref 'AWS::NoValue']
      SubDomainSettings:
        - Prefix: !If [!Equals [!Ref Environment, 'prod'], 'www', !Ref Environment]
          BranchName: !GetAtt AmplifyBranch.BranchName
        - Prefix: !If [!Equals [!Ref Environment, 'prod'], '', !Sub '${Environment}-api']
          BranchName: !GetAtt AmplifyBranch.BranchName

  # CloudWatch Dashboard
  AmplifyDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub 'PharmaCI-Frontend-${Environment}'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Amplify", "Requests", "App", "${AmplifyApp}"],
                  [".", "BytesDownloaded", ".", "."],
                  [".", "BytesUploaded", ".", "."]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Amplify Metrics"
              }
            }
          ]
        }

  # SSM Parameters for configuration
  APIEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/pharma-ci/${Environment}/api-endpoint'
      Type: String
      Value: 'https://api.placeholder.com'  # Will be updated by deployment script
      Description: 'API Gateway endpoint for frontend'

  VersionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/pharma-ci/${Environment}/version'
      Type: String
      Value: '1.0.0'
      Description: 'Application version'

  # CloudWatch Alarms
  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'PharmaCI-Frontend-HighErrorRate-${Environment}'
      AlarmDescription: 'High error rate on frontend'
      MetricName: 4xxError
      Namespace: AWS/Amplify
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: App
          Value: !GetAtt AmplifyApp.AppId

Outputs:
  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppId'

  AmplifyURL:
    Description: Amplify App URL
    Value: !If 
      - HasCustomDomain
      - !Sub 'https://${DomainName}'
      - !Sub 'https://${AmplifyBranch.BranchName}.${AmplifyApp.DefaultDomain}'
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyURL'

  AmplifyDomainStatus:
    Condition: HasCustomDomain
    Description: Custom domain status
    Value: !GetAtt AmplifyDomain.StatusReason
    Export:
      Name: !Sub '${AWS::StackName}-DomainStatus'